version: '3'
services:

  telegraf:
    image: "telegraf:1.13.4"
    environment:
      HOSTNAME: "obs"
      INFLUX_TOKEN: "DxroipSs9T-DILZfllbm3ALyxzGG8AKqsdreuQdnbgQHfvbbgSTJKSzqV2V96w7QyxJj8cHnA6abIOCsiMSrTw=="
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./telegraf:/etc/telegraf
    depends_on:
      - influxdb
    networks:
      - obs
      - gaworkshop

  jaeger:
    build:
      context: ./jaeger
    depends_on:
      - influxdb
    ports:
      - "16686:16686"
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_PLUGIN_CONFIGURATION_FILE: /opt/influxdb-plugin/config.yaml
      GRPC_STORAGE_PLUGIN_BINARY: /usr/local/bin/jaeger-influxdb-linux
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    volumes:
      - ./jaeger/influxdb-plugin:/opt/influxdb-plugin
    networks:
      - obs
      - gaworkshop

  influxdb:
    image: "quay.io/influxdb/influxdb:2.0.0-beta"
    ports:
      - "9999:9999"
    networks:
      - obs
      - gaworkshop

networks:
  obs:
  gaworkshop:
    external: true
